-- Основной скрипт развертывания базы


-- *** ОБЩИЕ НАСТРОЙКИ БАЗЫ ***




-- *** СХЕМА ***





-- *** ТАБЛИЦЫ ***
-- *ПОЛЬЗОВАТЕЛИ*
-- Пользователи
CREATE TABLE EC_USERS (
    USER_ID SERIAL PRIMARY KEY,
    USER_ROLE_ID NUMERIC NOT NULL,
    EMAIL VARCHAR(50),
    PASS VARCHAR(50),
    FIRST_NAME VARCHAR,
    SECOND_NAME VARCHAR,
    STATUS VARCHAR(50)
);
CREATE UNIQUE INDEX UI_EC_USERS_EMAIL ON EC_USER (EMAIL);
-- Перечень ролей, имеющихся в системе
CREATE TABLE EC_USER_ROLES (
    USER_ROLE_ID NUMERIC PRIMARY KEY,
    ROLE_NAME VARCHAR(50),
    ROLE_DESCRIPTION varchar(50)
);
-- *ОБРАЗОВАТЕЛЬНЫЕ КУРСЫ*
-- Образовательные курсы
CREATE TABLE EC_EDUCATIONAL_COURSES (
    EDUCATIONAL_COURSE_ID SERIAL PRIMARY KEY,
    HEADER VARCHAR,
    DESCRIPTION VARCHAR,
    PRICE NUMERIC NOT NULL
);
-- Задачи
CREATE TABLE EC_EDUCATIONAL_TASKS (
    EDUCATIONAL_TASK_ID SERIAL PRIMARY KEY
);
-- Задачи
CREATE TABLE EC_USER_COMPLETE_TASKS (
    USER_COMPLETE_TASK_ID NUMERIC PRIMARY KEY,
    USER_ID NUMERIC NOT NULL,
    EDUCATIONAL_TASK_ID NUMERIC NOT NULL
);

-- Подписки пользователей на курсы
CREATE TABLE EC_USER_COURSE_SUBSCRIPTIONS (
    USER_COURSE_SUBSCRIPTION_ID NUMERIC PRIMARY KEY,
    USER_ID NUMERIC NOT NULL,
    EDUCATIONAL_COURSE_ID NUMERIC NOT NULL,
    EXPIRATION_DATE TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Всевозможные достижения, получаемые пользователем при
-- выполнении каких-нибудь заданий
CREATE TABLE EC_EDUCATIONAL_ACHIEVEMENTS (
    EDUCATIONAL_ACHIEVEMENT_ID SERIAL PRIMARY KEY,
    USER_ID NUMERIC NOT NULL,
    DESCRIPTION VARCHAR
);

-- *СТАТЬИ*
-- Статьи
CREATE TABLE EC_ARTICLES (
    ARTICLE_ID SERIAL PRIMARY KEY,
    USER_ID NUMERIC,
    HEADER VARCHAR,
    TAGS JSON,
    DATE TIMESTAMP,
    CONTENT JSON NOT NULL
);
-- !!! Добавить каскадное удаление статья -> комментарии
-- Комментарии к статьям
CREATE TABLE EC_ARTICLE_COMMENTS (
    ARTICLE_COMMENT_ID SERIAL PRIMARY KEY,
    ARTICLE_ID NUMERIC NOT NULL,
    USER_ID NUMERIC,
    PARENT_COMMENT_ID NUMERIC,
    CONTENT VARCHAR,
    DATE TIMESTAMP
);
-- Закладки, сделанные пользователем
CREATE TABLE EC_USER_BOOKMARKED_ARTICLES (
    USER_BOOKMARKED_ARTICLE_ID SERIAL PRIMARY KEY,
    USER_ID NUMERIC NOT NULL,
    ARTICLE_ID NUMERIC NOT NULL
)
